# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5891c91d3c70a471730c1d46eb46f0228a2874155661770ca59eed0392d4ef70810a273807a4b81f0358ac89ba238c3dc589b7664a9494d222cdb506e9326317
  stripe_publishable_key: sk_test_vmjykYKePcwda62AuLGJ4HEl
  stripe_secret_key: pk_test_6mwRvJiMtv63LkYOXknJYvND

test:
  secret_key_base: 01ecdac6df1f44ee3877db188f064b8ba1e7ae54f9ac10c42f3d7d1399ba2a51d25beeb9e70cc0f5a8925e23461bc0bae2313aae8e0df0d855f74af85794d436

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
